### ISSUE TITLE
README: update at least "Enable GH App section"

### ISSUE THREAD

**Issue by Andersson007** [ansible/zuul-config#425]
https://github.com/ansible/zuul-config#enable-the-github-application
I think README came from old repo and it should be updated as I don't see tenants.yaml there.

Could anyone please update README not to be disturbed with asking for clarifications each time?

**Comment by goneri** [comment]
This is the file that replace the tenants.yaml https://github.com/ansible/zuul-config/blob/master/resources/ansible.yaml

**Comment by Andersson007** [comment]
@goneri do I need to change any other files? IIRC in https://github.com/ansible/zuul-config/pull/311 we changed only the file you mentioned and community.lbry is published by Zuul now

**Comment by Andersson007** [comment]
IIRC David told me that we need to add a collection to the second file zuul.d/projects.yaml only if there a `master` branch as default. There's a regexp for collections with `main`, so no need to add them. Is it correct?
